### ISSUE TITLE
Unused function definition changes the runtime behaviour of Whiley

### ISSUE THREAD

**Issue by utting** [Whiley/WhileyCompiler#552]
My program runs correctly and prints 15.

But when I define an additional function (called getMultiSized), but do not use that function anywhere, the program still compiles, but gives the following runtime error:
C02N3187FH04:oofoundations utting$ wyjc sum1a.whiley 
C02N3187FH04:oofoundations utting$ wyj sum1a
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: unknow type encountered (kind: 18)
	at wyjc.runtime.WyType.readNode(WyType.java:262)
	at wyjc.runtime.WyType.valueOf(WyType.java:186)
	at sum1a.<clinit>(./sum1a.whiley)
C02N3187FH04:oofoundations utting$ wyjc sum1b.whiley 
C02N3187FH04:oofoundations utting$ wyj sum1b
15
C02N3187FH04:oofoundations utting$ diff sum1a.whiley sum1b.whiley 
21,25c21,25
< function getMultiSized(Sized s) -> int:
<     if s is MultiSized:
< 	return s.size * s.count
<     else:
< 	return s.size
---
> //function getMultiSized(Sized s) -> int:
> //    if s is MultiSized:
> //	return s.size * s.count
> //    else:
> //	return s.size
C02N3187FH04:oofoundations utting$ 

I am using wdk-v0.3.37 on Mac OS X 10.11.2, using Java version "1.8.0_60".
I attach the file that works correctly: sum1b.whiley  (renamed to sum1b.txt)
and the one that gives the runtime error:  sum1a.whiley   (renamed to sum1a.txt)

[sum1a.txt](https://github.com/Whiley/WhileyCompiler/files/69529/sum1a.txt)
[sum1b.txt](https://github.com/Whiley/WhileyCompiler/files/69531/sum1b.txt)

**Comment by DavePearce** [comment]
Hey Mark,

Ok, interesting.  I'll have a look into that!

**Comment by DavePearce** [comment]
Reduced the test case to this:

<pre>
import whiley.lang.*

type SizeGetter is function(Sized) -> int
type Sized is { SizeGetter getSize, ... }
type MultiSized is { int count, SizeGetter getSize }

function getMultiSized(Sized s) -> int:
    if s is MultiSized:
	return s.count
    else:
	return 0

method main(System.Console sys):
    debug "Hello World"
</pre>

The reason the unused method is having an effect is because it's forcing the loading of a type constant to represent <code>MultiSized</code>.  For some reason, this is causing a problem.

**Comment by DavePearce** [comment]
By looking at the compiler code itself, can further reduce the test case to:

<pre>
import whiley.lang.*

type SizeGetter is function(Sized) -> int
type Sized is { SizeGetter getSize }

function f(null|SizeGetter x) -> int:
    if x is SizeGetter:
	return 1
    else:
	return 0

method main(System.Console sys):    
    debug "Hello World"
</pre>

The problem is related to the construction of a constant representing a function type.

**Comment by DavePearce** [comment]
Have now added <code>WyType.Function</code> and <code>WyType.Method</code>, which allow the above test cases to execute correctly.  However, runtime type testing of function and method types is not working.  An example is:

<pre>
import whiley.lang.*

type SizeGetter is function(Sized) -> int
type Sized is { SizeGetter getSize }

function f(null|SizeGetter x) -> int:
    if x is SizeGetter:
	return 1
    else:
	return 0

function getSize(Sized this) -> int:
    return 1

method main(System.Console sys):    
    int x = f(&getSize)
    sys.out.println(x)
</pre>

On the JVM this prints <code>0</code>, and crashes on the WyIL interpreter.

**Comment by DavePearce** [comment]
This issue is now resolved, and a new issue #554 is opened to handled the problem of runtime type tests.  There would appear to be another separate problem related to unions of function references.
