### ISSUE TITLE
Recursive method types fail to compile

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#641]
#640 introduced a bug. Consider the following program:

```
type mymethod is method()->(mymethod)

method m() -> mymethod:
    return &m

public export method test():
    mymethod x = m()
```

As you see the type `mymethod` is inhabited. Method `m` has that type.
But the compiler complains:

```
../../tests/valid/RecursiveType_Valid_29.whiley:1: empty type encountered
type mymethod is method()->(mymethod)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@richdougherty Can you please have a look at it?

**Comment by SebastianS90** [comment]
@DavePearce [wrote](https://github.com/Whiley/WhileyCompiler/pull/640#issuecomment-214568632) _(probably should have gone here instead)_ 
> This comes down to the question of what we consider to be "inhabited". Basically, function types should always be inhabited provided they have non-void parameters and returns. Method types may have void returns as well though.

To clarify, a method can have type `method()->()`.
But type `method()->(void)` should still be considered as uninhabited.

**Comment by DavePearce** [comment]
Hey Sebastian,

Yes, agreed.

**Comment by richdougherty** [comment]
Sorry about the bug. My plan was to be conservative with function inhabitation checks, but I guess I made a mistake. I'll take a look on Monday.

> Basically, function types should always be inhabited provided they have non-void parameters and returns.

Since functions are contravariant on their parameter types, couldn't a function with void parameters be inhabited? I'm not sure what the real world use case of a function type with void parameters, but we might want to be careful about declaring the function type as equivalent to void.

> To clarify, a method can have type method()->().
> But type method()->(void) should still be considered as uninhabited.

I agree. One of the things I was planning to discuss with @DavePearce was whether `method() -> void` means `-> ()` or `-> (void)`.

**Comment by SebastianS90** [comment]
The argument with contravariant parameters makes sense to me, as far as I remember we consider "void' to be a subtype of every type. So the type `method(void) ->() ` contains all methods that take one parameter and have no returns, which means it is inhabited.

**Comment by richdougherty** [comment]
Progress so far: https://github.com/Whiley/WhileyCompiler/compare/develop...richdougherty:bug/641-recursive-method-inhabitation

**Comment by DavePearce** [comment]
This is now fixed in `develop`.
