### ISSUE TITLE
Development and Release Procedures and Processes

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#684]
An important challenge (I think) is to simplify the release process and increase the rate of releases. This should help to reduce the "pain" of making an individual release.  Up to this point, the following procedures have been followed for development and deployment:
1. `master` branch contains latest stable release.  All commits are tagged as releases.
2. `develop` branch contains current development snapshot.  When ready, this is merged into `master` to create a new release.
3. `feature` and `bugfix` branches were forked from `develop` and merged back in with `--no-ff`

Each release was then manually tagged and a blog post written about it.  However, this process has now become too long winded and I need to streamline the process.  Some factors:
- **Compiler split**.  The WhileyCompile repository is now split up into several different projects (e.g. WhileyCompilerCollection, WhileyCompiler, etc).  _This means that individual components can move at their own pace with respect to versions_.
- **Maven**.  I'm planning to start using Maven to help manage dependencies, as this has become more of a problem now that there are multiple repositories  (actually am using Maven already to handle the Jasm dependency which I finally got hosted there)
- **Master vs Develop**.  I have seen it mentioned that have a division between `master` and `develop` is not necessarily that helpful.  Basically, because everything that goes into master is a tagged release, so you might as well just have one branch and tag directly from there.

Overall, this needs some thought.  In particular, I should only be making blog posts for interesting and larger releases, and then just shipping incremental releases immediately.

@richdougherty Interested in your thoughts on this.

**Comment by richdougherty** [comment]
> Compiler split

There are pros and cons for this. There's more work involved with separate repos, but it is easier to run different release cycles for different artifacts, if that's desirable. I think the main benefit for having different repos and release cycles is that it allows different committers to work on parts of the codebase independently. E.g. if you had other committers working on an Eclipse plugin, that could be in a separate repo with different versioning from the main part of Whiley.

> Maven

Good idea to go to a build tool that manages dependencies. If you haven't settled on Maven then take a look at Gradle. I think it's considered to be a bit more modern and easy to use. Maven is still widely used though.

> Master vs Develop

I think most projects do just use a master branch for developing on, then make a branch for each major version and tags for each minor versions. With this approach you might occasionally have extra work if you perform fixes on master and then need to backport them to the version branch. You might actually be able to get away with only tags on master, since you're still in a pre-release phase.

**Comment by DavePearce** [comment]
Hey Rich,

Am currently in Zurich on Holiday for a few weeks ... so haven't had much time to think about this.  Basically, I think what you said is one of the reasons:

> I think the main benefit for having different repos and release cycles is that it allows different committers to work on parts of the codebase independently

I should have a think about Gradle then.  Am not completely wedded to Maven at this stage.
