### ISSUE TITLE
Future: requires/precondition overloading

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#725]
Overloading functions on requires clauses would be an interesting take on overloading, but:

1. It might be difficult to do for complex properties, so maybe a subset is more tractable (e.g. without exists-quantifiers)

2. One might not want to overload on all the requires clauses for a function only a subset.

So what if Whiley had a syntax for it. Not sure what it should be, but conceptually:

function f(x)
overload on requires x>0
requires x < 1000.
   ...

**Comment by DavePearce** [comment]
_(For reference, these are my comments from the forum)_

Yes, I have thought about this.  However, in the end, I am somewhat hesitant and decided against it for now.  The main issue for me at the moment (which may seem surprising) is that of binary compatibility.  Specifically, what kind of name mangling makes sense.  For overloading on types, it's actually quite easy since we can produce a string which uniquely encodes the parameter types.  But, for arbitrary pre-conditions, this is actually quite difficult.  We need at least some kind of mangling to avoid ambiguity between functions which differ only in their requires clauses.  A simple one is simply to use an index based on their occurrence in the source file, but this is quite brittle.  For example, if the ordering changes, then existing code would not be binary compatible.

Anyhow, one option I have been considering is to allow overloading on nominal type information which would give some of the effect you are after.  For example, it would mean you could write this:
```
type pos is (int x) where x > 0
type neg is (int x) where x < 0

function f(pos x) -> (int r):
    return x

function f(neg y) -> (int r):
    return y + 1
```
Then, in the case of an invocation f(x) where x has type e.g. pos then it resolves automatically as expected.  If, however, x had type e.g. int then you would need to manually cast in order to resolve the ambiguity.  Am also unsure whether this is a good idea or not ... there are certainly pros and cons both ways.

**Comment by DavePearce** [comment]
This is related to #702.

However, at this time, I am going to close this issue.  Basically, I don't this is something we will support in the near future.  You could try to write it up as an RFC.
