### ISSUE TITLE
Backend: evaluation of target-languages

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#739]
Here I will try to sort out target-languages that have a good match to Whiley IR semantics.
And map out some requirements to see if they can share backend features.
(This first post will be edited over time)

**Read docs on**
Ruby
Crystal
Scala, Groovy, Clojure
Lua
OCaml
Perl 6
R
Julia 

**Close match**
Python: integers, arrays, tuples... seems to be a good match.
Matlab: I have to test, but I think it should work out somehow

**Close match if numbers are bounded**
TypeScript (base on JavaScript engine)
Dart (base on JavaScript engine?)
Php (base on JavaScript engine?)

**May need some custom library types**
Go
Swift
Java
C#

**Not a very close match, but important**
Objective-C is the easiest route to providing high performance code to Swift.
C++,  Ada?, Rust, Chapel, Pony?

**Others**
Vala, Pascal, D, Nimrod, Haxe

Jai: Jonathan Blow seems to have some interest in correctness checks https://youtu.be/gWv_vUgbmug?t=48m11s

**Unsuitable**
Erlang, Elixir, Haskell, Lisp...

**Comment by DavePearce** [comment]
Realistically, I think you need to build a back end for some language before you can make this judgment.  Understanding the pain points with other languages is hard.

This issue is somehow off topic here. It's more of a to-do list than an issue.  I think perhaps you should create a repository e.g. for `WhileyLLVM` or maybe `Whiley++` and put it there...
