### ISSUE TITLE
Feature request: minimizing constants

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#741]
Provide the programmer with a convenience feature that minimizes a constant within a range [N,M] or over a set 1,2,4,8,16 or similar. This is useful when writing algorithms that for performance reasons should stay below M or within a specific set of values.

However at least one value in the set should be considered valid without verification. That way the compiler can still compile the program if the verifier is turned off and the language should specify deterministic heuristics for what the constant would be with verification turned off.

One possibility is to extend the language with a syntax like:
~~`constant limit is minimize N..M`~~~

With verification turned off, the constant limit would be set to M. With verification turned on the compiler could do a binary search like M, (N+(M-N)/2) under the assumption that the implicit cost function is monotonic. This monoticity could be given with a compiler hint `@monotonic` after the constant definition, or the compiler could just assume it.

But maybe a more general syntax would be better:

`constant a is choose N..M`
`constant b is choose 1,2,(N*2)..(M**3),a*4`

The cost function could be implictly given as:

`constant a is choose N..M @minimize `
`constant b is choose 1,2,(N*2)..(M**3),a*4 @maximize`

Then the compiler could assume a default optimization order by first minimizing a, then maximizing b.

A later extension could allow the programmer to define an explicit cost function over `a` and `b`, e.g. `@cost(a*30+b*b)` , that is to be minimized. This might be useful for optimizing algorithms with errorbounds, e.g. increase the number of iterations in nested loops until the error-bound assert passes. With a cost function the non-verified default could be given explicitly:

`constant c is choose N..M default (N+M)/2 `

**The implementation could use the existing verifier and repeatedly run it using a binary search. No changes to the existing verifier is needed.** Therefore one could get this functionality in Whiley at an early stage without making the verifier more complicated. A later version of the verifier could incorporate the semantics for better performance.

The worst case complexity over a monotonic range N..M with for a single verification pass with cost V would be O( log(M-N) * V) for one constant. For C constants with a range of values that is limited to R integers the worst case complexity should be O(C * log(R) * V).

Other strategies such a genetic search can be used as well since the compiler
is free to choose any integer in the allowed set. Therefore it could easily be extended with `@` hints that a given compiler may choose to ignore, by most compilers should try to heed at lest `@minimize` and `@maximize`.

**Comment by bambinella** [comment]
This could feature could also be used for letting the compiler choose between different algorithm based on performance, memory or "stability" estimates. Then these metrics would be in the cost-equation.

**Comment by DavePearce** [comment]
So, roughly speaking, you want to use the compiler to perform some kind of search of an optimisation space to find a good solution (from a performance perspective).

This is not a language feature --- it is a compiler optimisation, or perhaps a tool or library for code generation.  The problem is that the semantic meaning of this feature is difficult to capture (e.g. in the language specification).  We can actually reduce the proposal to the introduction of a non-deterministic choice operator: `choose`.  See:

https://en.wikipedia.org/wiki/Nondeterministic_programming

Such an operator could be used within arbitrary expressions.  But, such an operator is not really a good idea for a general purpose language.  For example, debugging is very difficult without determinism (this is why debugging concurrent code is difficult).  There are languages which have non-deterministic operators though, such as Dykstra's so-called language of guarded commands:

https://en.wikipedia.org/wiki/Guarded_Command_Language

**However**, the basic idea of doing a search space exploration of a parameter space for the purposes code optimisation is definitely a thing.  There are lots of papers on this.  Just yesterday even I was talking to a group in London which do exactly this for the so-called "SLAM" algorithm:

https://arxiv.org/abs/1410.2167

**Comment by DavePearce** [comment]
I think you should migrate this into the wiki.

**Comment by DavePearce** [comment]
See also these pointers:

* http://www.icl.utk.edu/sites/icl/files/publications/2016/icl-utk-902-2016.pdf

* http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.136.8643&rep=rep1&type=pdf

Turns out my old supervisor at Imperial College does a lot of this kind of thing.  It's a very interesting and active area of research ...

**Comment by DavePearce** [comment]
I should add also one possible avenue here is through the use of `native` constants.  For example:

```
native constant c
```

This is something I'm considering to allow constants to be defined by the runtime.  With such a constant, an extended code generator could then select an optimal value based on some kind of exploration.

Furthermore, I want to change the constant syntax to be in line with variable declarations.  So it would look e.g. like this:

```
native int c
```

Using the type, you could then constraint the possible values of `c` accordingly.

**Comment by bambinella** [comment]
> I think you should migrate this into the wiki.

Ok, what should the link-title be though?

"Constraint solving of constants"?

**Comment by DavePearce** [comment]
Well, if the primary reason is to generate better code, then I would use a title such as "Search-Based Code Optimisation".  But, whatever works for you really.
