### ISSUE TITLE
False index out of bounds error when asserting with a quantifier + an array

### ISSUE THREAD

**Issue by dylan-chong** [Whiley/WhileyCompiler#807]
```
function f() -> (int[] a):
    a = [1,2,3]
    
    assert a[0] == 1 // ok
    assert a[1] == 2 // ok
    assert a[2] == 3 // ok
    assert (all { j in 1..1 | a[j] >= 0 }) // index out of bounds (negative)

    return a
```

**Comment by DavePearce** [comment]
Hey Dylan,

Yes, this is a problem with the way preconditions for expressions are checked.  There were some existing issues for it.  See #800 

In fact, this issue has been fixed in the latest released version of the Whiley Compiler.  However, that is not live on whileylabs.com at this time.  The reason being that it additionally changes the syntax of Whiley slightly, and I wanted to make sure the SWEN224 course coordinator was happy with this before I did it.  However, I haven't heard back from him ... but I'm coming in today, so will try and track him down.
